### ISSUE TITLE
Lots of stories broken in Canvas view

### ISSUE THREAD

**Issue by dhruvkb** [WordPress/openverse-frontend#1135]
## Description
Many stories in the Storybook on `main` are broken. This might be a consequence of updating it to Storybook 6.4 although there are no breaking changes in the changelog. Strangely enough, the smoke test passes.

## Reproduction

Visit the ["Components/VAudioThumbnail/Square" story](https://wordpress.github.io/openverse-frontend/?path=/story/components-vaudiothumbnail--square) in the "Canvas" view. There might be other stories broken in a similar fashion.

## Expectation

The stories should render.

## Additional context

The broken stories can be fixed by using the composition API format with a `setup()` function. See #1134 which fixes the stories for  "Components/VLicense".

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

**Comment by sarayourfriend** [comment]
@dhruvkb this is fixed now right?

**Comment by dhruvkb** [comment]
I'm not sure. I'll quickly check and update the ticket.

**Comment by dhruvkb** [comment]
The following stories still have issues:
- [ ] `VContentLink`
- [ ] `VContentSwitcherPopover`
- [ ] `VItemGroup`
- [ ] `VModal`
- [ ] `VPill`
