### ISSUE TITLE
Single audio result view has horizontal scroll on mobile

### ISSUE THREAD

**Issue by krysal** [WordPress/openverse-frontend#781]
## Description

As the title says, this page has unwanted horizontal scrolling on mobile view.

## Reproduction

1. Run the project and go to this page (for any audio) on a mobile or emulation device.
4. See error.

## Expectation

The page should not have horizontal scrolling.

## Screenshots

https://user-images.githubusercontent.com/9145885/152043435-d0e4a1cb-4822-407d-ad8b-8492e670ec5b.mp4

## Resolution

- [x] 🙋 I would be interested in resolving this bug.

**Comment by zackkrida** [comment]
@krysal before you look at this, I believe it's fixed in #744!

**Comment by krysal** [comment]
@zackkrida Last time I checked was still an issue on both, `main` and in your branch. I see it's fixed there now, great!
